# This file was generated by GoReleaser. DO NOT EDIT.
cask "termodoro" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "b91c18aeccec1dee7c1c068e88e05a2447780792610b49a3040ed3dfba78a475"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_macOS_amd64.tar.gz"
    end
    on_arm do
      sha256 "684dd7ae40b6f5e6f168f92ce483cda16a7af593ab4ce9ed489733c47202a6bc"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e0f04b48887c6ed771ef0d1cb0521ce20e4cc00a9b604d2497f84df785b9a74"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a5e95ac3ada714edac7fb5d646a743703b89e11dab71897b94d840fca86d84e"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termodoro"
  desc "Termodoro is a terminal-based Pomodoro timer"
  homepage "https://github.com/hrushik98/termodoro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termodoro"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termodoro"]
    end
  end

  # No zap stanza required

end
