# This file was generated by GoReleaser. DO NOT EDIT.
cask "termodoro" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "fc38d7f9285256f18024fc9647f79de55f20c0fc5abebd764a009292307b93dc"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_macOS_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a78c710eaa8ec829680849e2101ac43d92b969d50bef6ca6fa8f8a8b2e62937"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7165ca79ed9286d3352a98c1b88806980a1f147201cc0e933b66cb67d31b58bd"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59aa0c6ea8cbdd45589f9d0efdcbdac85f4fc581807a18bda7635a3a5d04239e"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termodoro"
  desc "Termodoro is a terminal-based Pomodoro timer"
  homepage "https://github.com/hrushik98/termodoro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termodoro"

  # No zap stanza required

end
