# This file was generated by GoReleaser. DO NOT EDIT.
cask "termodoro" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b0b3c6a0b648f341e4cee328ff3843f405dda68c21d2c21b3c43d3390e26041a"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_macOS_amd64.tar.gz"
    end
    on_arm do
      sha256 "043a5b664116b0b725aaa8ccc2f0edff3cb4f7567a8126218a3bbfa0c0bf38cd"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "86577effe5b0b96adbdef4b69166ca0f77ba2a809fc171ed49c402843bec1c1c"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fee60adbec327b73d7790468f166976a211e9400dea0cdf4a039948756f44986"
      url "https://github.com/hrushik98/termodoro/releases/download/v#{version}/termodoro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termodoro"
  desc "Termodoro is a terminal-based Pomodoro timer"
  homepage "https://github.com/hrushik98/termodoro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termodoro"

  # No zap stanza required

end
